allowBuilds:
  esbuild: true
  msw: true

packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  eslint: '^10.3.0'
  typescript: '~6.0.2'
  react: '^19.2.6'
  react-dom: '^19.2.6'
  '@tanstack/react-query': '^5.101.0'
  '@tanstack/react-router': '^1.170.11'
  '@tanstack/router-plugin': '^1.168.18'

