/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/~__root'
import { Route as AuthRouteImport } from './routes/~_auth'
import { Route as AuthRecruitRouteRouteImport } from './routes/~_auth/~recruit/~route'
import { Route as AuthMembersRouteRouteImport } from './routes/~_auth/~members/~route'
import { Route as TestIndexRouteImport } from './routes/~test/~index'
import { Route as AuthrootIndexRouteImport } from './routes/~_auth/~(root)/~index'
import { Route as AuthRecruitTemplatesIndexRouteImport } from './routes/~_auth/~recruit/~templates/~index'
import { Route as AuthRecruitSchedulesIndexRouteImport } from './routes/~_auth/~recruit/~schedules/~index'
import { Route as AuthRecruitMailIndexRouteImport } from './routes/~_auth/~recruit/~mail/~index'
import { Route as AuthRecruitApplicantsIndexRouteImport } from './routes/~_auth/~recruit/~applicants/~index'
import { Route as AuthMembersListIndexRouteImport } from './routes/~_auth/~members/~list/~index'
import { Route as AuthRecruitSchedulesNewIndexRouteImport } from './routes/~_auth/~recruit/~schedules/~new/~index'
import { Route as AuthRecruitMailNewIndexRouteImport } from './routes/~_auth/~recruit/~mail/~new/~index'

const SigninIndexLazyRouteImport = createFileRoute('/signin/')()

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninIndexLazyRoute = SigninIndexLazyRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/~signin/~index.lazy').then((d) => d.Route),
)
const AuthRecruitRouteRoute = AuthRecruitRouteRouteImport.update({
  id: '/recruit',
  path: '/recruit',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMembersRouteRoute = AuthMembersRouteRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthRoute,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/~test/~index.lazy').then((d) => d.Route))
const AuthrootIndexRoute = AuthrootIndexRouteImport.update({
  id: '/(root)/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecruitTemplatesIndexRoute =
  AuthRecruitTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthRecruitRouteRoute,
  } as any)
const AuthRecruitSchedulesIndexRoute =
  AuthRecruitSchedulesIndexRouteImport.update({
    id: '/schedules/',
    path: '/schedules/',
    getParentRoute: () => AuthRecruitRouteRoute,
  } as any)
const AuthRecruitMailIndexRoute = AuthRecruitMailIndexRouteImport.update({
  id: '/mail/',
  path: '/mail/',
  getParentRoute: () => AuthRecruitRouteRoute,
} as any)
const AuthRecruitApplicantsIndexRoute =
  AuthRecruitApplicantsIndexRouteImport.update({
    id: '/applicants/',
    path: '/applicants/',
    getParentRoute: () => AuthRecruitRouteRoute,
  } as any)
const AuthMembersListIndexRoute = AuthMembersListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => AuthMembersRouteRoute,
} as any)
const AuthRecruitSchedulesNewIndexRoute =
  AuthRecruitSchedulesNewIndexRouteImport.update({
    id: '/schedules/new/',
    path: '/schedules/new/',
    getParentRoute: () => AuthRecruitRouteRoute,
  } as any)
const AuthRecruitMailNewIndexRoute = AuthRecruitMailNewIndexRouteImport.update({
  id: '/mail/new/',
  path: '/mail/new/',
  getParentRoute: () => AuthRecruitRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthrootIndexRoute
  '/test/': typeof TestIndexRoute
  '/members': typeof AuthMembersRouteRouteWithChildren
  '/recruit': typeof AuthRecruitRouteRouteWithChildren
  '/signin/': typeof SigninIndexLazyRoute
  '/members/list/': typeof AuthMembersListIndexRoute
  '/recruit/applicants/': typeof AuthRecruitApplicantsIndexRoute
  '/recruit/mail/': typeof AuthRecruitMailIndexRoute
  '/recruit/schedules/': typeof AuthRecruitSchedulesIndexRoute
  '/recruit/templates/': typeof AuthRecruitTemplatesIndexRoute
  '/recruit/mail/new/': typeof AuthRecruitMailNewIndexRoute
  '/recruit/schedules/new/': typeof AuthRecruitSchedulesNewIndexRoute
}
export interface FileRoutesByTo {
  '/test': typeof TestIndexRoute
  '/members': typeof AuthMembersRouteRouteWithChildren
  '/recruit': typeof AuthRecruitRouteRouteWithChildren
  '/signin': typeof SigninIndexLazyRoute
  '/': typeof AuthrootIndexRoute
  '/members/list': typeof AuthMembersListIndexRoute
  '/recruit/applicants': typeof AuthRecruitApplicantsIndexRoute
  '/recruit/mail': typeof AuthRecruitMailIndexRoute
  '/recruit/schedules': typeof AuthRecruitSchedulesIndexRoute
  '/recruit/templates': typeof AuthRecruitTemplatesIndexRoute
  '/recruit/mail/new': typeof AuthRecruitMailNewIndexRoute
  '/recruit/schedules/new': typeof AuthRecruitSchedulesNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/test/': typeof TestIndexRoute
  '/_auth/members': typeof AuthMembersRouteRouteWithChildren
  '/_auth/recruit': typeof AuthRecruitRouteRouteWithChildren
  '/signin/': typeof SigninIndexLazyRoute
  '/_auth/(root)/': typeof AuthrootIndexRoute
  '/_auth/members/list/': typeof AuthMembersListIndexRoute
  '/_auth/recruit/applicants/': typeof AuthRecruitApplicantsIndexRoute
  '/_auth/recruit/mail/': typeof AuthRecruitMailIndexRoute
  '/_auth/recruit/schedules/': typeof AuthRecruitSchedulesIndexRoute
  '/_auth/recruit/templates/': typeof AuthRecruitTemplatesIndexRoute
  '/_auth/recruit/mail/new/': typeof AuthRecruitMailNewIndexRoute
  '/_auth/recruit/schedules/new/': typeof AuthRecruitSchedulesNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test/'
    | '/members'
    | '/recruit'
    | '/signin/'
    | '/members/list/'
    | '/recruit/applicants/'
    | '/recruit/mail/'
    | '/recruit/schedules/'
    | '/recruit/templates/'
    | '/recruit/mail/new/'
    | '/recruit/schedules/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/test'
    | '/members'
    | '/recruit'
    | '/signin'
    | '/'
    | '/members/list'
    | '/recruit/applicants'
    | '/recruit/mail'
    | '/recruit/schedules'
    | '/recruit/templates'
    | '/recruit/mail/new'
    | '/recruit/schedules/new'
  id:
    | '__root__'
    | '/_auth'
    | '/test/'
    | '/_auth/members'
    | '/_auth/recruit'
    | '/signin/'
    | '/_auth/(root)/'
    | '/_auth/members/list/'
    | '/_auth/recruit/applicants/'
    | '/_auth/recruit/mail/'
    | '/_auth/recruit/schedules/'
    | '/_auth/recruit/templates/'
    | '/_auth/recruit/mail/new/'
    | '/_auth/recruit/schedules/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  TestIndexRoute: typeof TestIndexRoute
  SigninIndexLazyRoute: typeof SigninIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof SigninIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/recruit': {
      id: '/_auth/recruit'
      path: '/recruit'
      fullPath: '/recruit'
      preLoaderRoute: typeof AuthRecruitRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/members': {
      id: '/_auth/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthMembersRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/(root)/': {
      id: '/_auth/(root)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthrootIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/recruit/templates/': {
      id: '/_auth/recruit/templates/'
      path: '/templates'
      fullPath: '/recruit/templates/'
      preLoaderRoute: typeof AuthRecruitTemplatesIndexRouteImport
      parentRoute: typeof AuthRecruitRouteRoute
    }
    '/_auth/recruit/schedules/': {
      id: '/_auth/recruit/schedules/'
      path: '/schedules'
      fullPath: '/recruit/schedules/'
      preLoaderRoute: typeof AuthRecruitSchedulesIndexRouteImport
      parentRoute: typeof AuthRecruitRouteRoute
    }
    '/_auth/recruit/mail/': {
      id: '/_auth/recruit/mail/'
      path: '/mail'
      fullPath: '/recruit/mail/'
      preLoaderRoute: typeof AuthRecruitMailIndexRouteImport
      parentRoute: typeof AuthRecruitRouteRoute
    }
    '/_auth/recruit/applicants/': {
      id: '/_auth/recruit/applicants/'
      path: '/applicants'
      fullPath: '/recruit/applicants/'
      preLoaderRoute: typeof AuthRecruitApplicantsIndexRouteImport
      parentRoute: typeof AuthRecruitRouteRoute
    }
    '/_auth/members/list/': {
      id: '/_auth/members/list/'
      path: '/list'
      fullPath: '/members/list/'
      preLoaderRoute: typeof AuthMembersListIndexRouteImport
      parentRoute: typeof AuthMembersRouteRoute
    }
    '/_auth/recruit/schedules/new/': {
      id: '/_auth/recruit/schedules/new/'
      path: '/schedules/new'
      fullPath: '/recruit/schedules/new/'
      preLoaderRoute: typeof AuthRecruitSchedulesNewIndexRouteImport
      parentRoute: typeof AuthRecruitRouteRoute
    }
    '/_auth/recruit/mail/new/': {
      id: '/_auth/recruit/mail/new/'
      path: '/mail/new'
      fullPath: '/recruit/mail/new/'
      preLoaderRoute: typeof AuthRecruitMailNewIndexRouteImport
      parentRoute: typeof AuthRecruitRouteRoute
    }
  }
}

interface AuthMembersRouteRouteChildren {
  AuthMembersListIndexRoute: typeof AuthMembersListIndexRoute
}

const AuthMembersRouteRouteChildren: AuthMembersRouteRouteChildren = {
  AuthMembersListIndexRoute: AuthMembersListIndexRoute,
}

const AuthMembersRouteRouteWithChildren =
  AuthMembersRouteRoute._addFileChildren(AuthMembersRouteRouteChildren)

interface AuthRecruitRouteRouteChildren {
  AuthRecruitApplicantsIndexRoute: typeof AuthRecruitApplicantsIndexRoute
  AuthRecruitMailIndexRoute: typeof AuthRecruitMailIndexRoute
  AuthRecruitSchedulesIndexRoute: typeof AuthRecruitSchedulesIndexRoute
  AuthRecruitTemplatesIndexRoute: typeof AuthRecruitTemplatesIndexRoute
  AuthRecruitMailNewIndexRoute: typeof AuthRecruitMailNewIndexRoute
  AuthRecruitSchedulesNewIndexRoute: typeof AuthRecruitSchedulesNewIndexRoute
}

const AuthRecruitRouteRouteChildren: AuthRecruitRouteRouteChildren = {
  AuthRecruitApplicantsIndexRoute: AuthRecruitApplicantsIndexRoute,
  AuthRecruitMailIndexRoute: AuthRecruitMailIndexRoute,
  AuthRecruitSchedulesIndexRoute: AuthRecruitSchedulesIndexRoute,
  AuthRecruitTemplatesIndexRoute: AuthRecruitTemplatesIndexRoute,
  AuthRecruitMailNewIndexRoute: AuthRecruitMailNewIndexRoute,
  AuthRecruitSchedulesNewIndexRoute: AuthRecruitSchedulesNewIndexRoute,
}

const AuthRecruitRouteRouteWithChildren =
  AuthRecruitRouteRoute._addFileChildren(AuthRecruitRouteRouteChildren)

interface AuthRouteChildren {
  AuthMembersRouteRoute: typeof AuthMembersRouteRouteWithChildren
  AuthRecruitRouteRoute: typeof AuthRecruitRouteRouteWithChildren
  AuthrootIndexRoute: typeof AuthrootIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthMembersRouteRoute: AuthMembersRouteRouteWithChildren,
  AuthRecruitRouteRoute: AuthRecruitRouteRouteWithChildren,
  AuthrootIndexRoute: AuthrootIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  TestIndexRoute: TestIndexRoute,
  SigninIndexLazyRoute: SigninIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
