/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/~__root'
import { Route as AuthRouteImport } from './routes/~_auth'
import { Route as AuthMembersRouteRouteImport } from './routes/~_auth/~members/~route'
import { Route as TestIndexRouteImport } from './routes/~test/~index'
import { Route as AuthIndexRouteImport } from './routes/~_auth/~index'
import { Route as AuthMembersListIndexRouteImport } from './routes/~_auth/~members/~list/~index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMembersRouteRoute = AuthMembersRouteRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthRoute,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/~test/~index.lazy').then((d) => d.Route))
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMembersListIndexRoute = AuthMembersListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => AuthMembersRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/test/': typeof TestIndexRoute
  '/members': typeof AuthMembersRouteRouteWithChildren
  '/members/list/': typeof AuthMembersListIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/test': typeof TestIndexRoute
  '/members': typeof AuthMembersRouteRouteWithChildren
  '/members/list': typeof AuthMembersListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/test/': typeof TestIndexRoute
  '/_auth/members': typeof AuthMembersRouteRouteWithChildren
  '/_auth/members/list/': typeof AuthMembersListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test/' | '/members' | '/members/list/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test' | '/members' | '/members/list'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/'
    | '/test/'
    | '/_auth/members'
    | '/_auth/members/list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  TestIndexRoute: typeof TestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/members': {
      id: '/_auth/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthMembersRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/members/list/': {
      id: '/_auth/members/list/'
      path: '/list'
      fullPath: '/members/list/'
      preLoaderRoute: typeof AuthMembersListIndexRouteImport
      parentRoute: typeof AuthMembersRouteRoute
    }
  }
}

interface AuthMembersRouteRouteChildren {
  AuthMembersListIndexRoute: typeof AuthMembersListIndexRoute
}

const AuthMembersRouteRouteChildren: AuthMembersRouteRouteChildren = {
  AuthMembersListIndexRoute: AuthMembersListIndexRoute,
}

const AuthMembersRouteRouteWithChildren =
  AuthMembersRouteRoute._addFileChildren(AuthMembersRouteRouteChildren)

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthMembersRouteRoute: typeof AuthMembersRouteRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthMembersRouteRoute: AuthMembersRouteRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  TestIndexRoute: TestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
